### ISSUE TITLE
JDK installed via "brew install java" is not detected correctly

### ISSUE THREAD

**Issue by testforstephen** [Eskibear/node-jdk-utils#2]
When using `brew install java` to install a JDK on macOS, it will recommend user to append `/usr/local/opt/openjdk/bin` to the PATH environment variable. If I use the `jdk-utils` lib to detect the Java home directory from the PATH, it returns `/usr/local/opt/openjdk` as the Java home directory.

However, this is not a valid JDK home directory. It only has symbolic links to the `bin` folder, and other folders such as `lib` are not included.

![image](https://user-images.githubusercontent.com/14052197/146707407-7e29aa38-a378-4746-ba16-c4e216cf9ab7.png)

The actual JDK home is placed at the subfolder `libexec`.
![image](https://user-images.githubusercontent.com/14052197/146707337-8751618b-0c7c-4953-af63-2e39d6b89b8e.png)

**Comment by Eskibear** [comment]
https://github.com/Eskibear/node-jdk-utils/blob/e353fe7db71cf493ff7a25cebc98cc98362adf9e/src/from/envs.ts#L6-L9

https://github.com/Eskibear/node-jdk-utils/blob/e353fe7db71cf493ff7a25cebc98cc98362adf9e/src/utils.ts#L4-L7

Currently I filter items in `PATH` which looks like a bin folder of a java distribution, and only validate existence of file `java` or `javac`. 

Probably we should:
a) validate existence of `release` file
b) resolve symbolic links of the binary file to cover homebrew.

**Comment by testforstephen** [comment]
Resolving symbolic link when detecting $PATH looks a good approach to cover such kind of issue.

Another improvement is to add the brew installation locations to the candidate list.

- /usr/local/Cellar/openjdk/
- /opt/homebrew/Cellar/openjdk/

**Comment by Eskibear** [comment]
@testforstephen 
Fixed in `jdk-utils@0.4.0`. You can give it a try.

**Comment by Eskibear** [comment]
I added a CLI in 0.4.1 for convenience, you can run below commands to quickly list all detected runtimes.
```
npx jdk-utils@0.4.1
```
