### ISSUE TITLE
Gradle toolchains Support

### ISSUE THREAD

**Issue by cypher256** [Eskibear/node-jdk-utils#9]
Thank you for providing such a wonderful library.
Is it possible to support detection of JDKs managed by Gradle toolchains?

Gradle Toolchains (~/.gradle/jdks)
https://docs.gradle.org/current/userguide/toolchains.html#sec:provisioning

**Comment by Eskibear** [comment]
You can help yourself by submitting a PR. E.g. you can follow #7 

BTW, is it always `~/.gradle/jdks` or you can customize it via some env?

**Comment by cypher256** [comment]
It can be customized with the environment variable GRADLE_USER_HOME.
I will send a PR later :)

**Comment by Eskibear** [comment]
0.4.5 published with tag `next`.  you can test locally via `npx jdk-utils@next`, see if it detects all theses installations.

**Comment by Eskibear** [comment]
I'm closing this as v0.4.6 has been released, thank you @cypher256 !
